name: FGD Build and Folder Copy
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install srctools
        run: .\install_srctools.bat

      - name: FGD build and folder copy
        run: .\build.bat all

      - name: Artifact upload
        uses: actions/upload-artifact@v2
        with:
          name: FGD-Build
          path: ./build/*
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install srctools
        run: bash ./install_srctools.sh

      - name: FGD build and folder copy
        run: bash ./build.sh all
